workflows:
  ios-workflow:
    scripts:
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
          
      - name: Fix Swift issues
        script: |
          # Clean build folder
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          
          # Set Swift version
          echo "SWIFT_VERSION = 5.0" >> ios/Flutter/Generated.xcconfig
          
      - name: Install pods
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate
          pod install --repo-update
          cd ..
      
      - name: Fix privacy bundle build issue (url_launcher_ios)
        script: |
          # CRITICAL FIX: url_launcher_ios privacy bundle build failure
          # This is a known issue with CocoaPods + Flutter on Xcode 15+
          
          # Clean any corrupted build artifacts
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          
          # Force clean and rebuild
          flutter clean
          flutter pub get
          
          # Reinstall pods after clean
          cd ios
          pod install --repo-update
          cd ..
          
      - name: Build iOS
        script: |
          # Use --release instead of --debug to avoid privacy bundle issues
          flutter build ipa --release \
            --export-options-plist /Users/builder/export_options.plist