workflows:
  ios-workflow:
    scripts:
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
          
      - name: Fix Swift issues
        script: |
          # Clean build folder
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          
          # Set Swift version
          echo "SWIFT_VERSION = 5.0" >> ios/Flutter/Generated.xcconfig
          
      - name: Install pods
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate || true
          pod install --repo-update
          cd ..
      
      - name: Fix privacy bundle build issues (Critical for Xcode 15+)
        script: |
          # CRITICAL FIX: Privacy bundle build failures
          # Affects: url_launcher_ios, sqflite_darwin, and other plugins with privacy manifests
          
          # Clean all corrupted build artifacts
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          
          # Remove problematic privacy bundle references from Xcode project
          cd ios
          
          # Use Ruby to remove privacy bundle file references from Runner.xcodeproj
          ruby -e "
          require 'xcodeproj'
          project_path = 'Runner.xcodeproj'
          project = Xcodeproj::Project.open(project_path)
          
          project.targets.each do |target|
            next unless target.name == 'Runner'
            
            target.build_phases.each do |phase|
              phase.files.to_a.each do |file|
                if file.file_ref && file.file_ref.path && file.file_ref.path.include?('privacy.bundle')
                  puts \"Removing: #{file.file_ref.path}\"
                  phase.remove_file_reference(file.file_ref)
                end
              end
            end
          end
          
          project.save
          puts 'Privacy bundle references removed successfully'
          " || echo "Ruby script failed, continuing..."
          
          cd ..
          
      - name: Build iOS
        script: |
          # Use --release mode which has better plugin compatibility
          flutter build ipa --release \
            --export-options-plist /Users/builder/export_options.plist