workflows:
  ios-workflow:
    scripts:
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
          
      - name: Fix Swift issues
        script: |
          # Clean build folder
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          
          # Set Swift version
          echo "SWIFT_VERSION = 5.0" >> ios/Flutter/Generated.xcconfig
          
      - name: Install pods
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate || true
          pod install --repo-update
          
          # Run privacy bundle fix script
          ruby fix_privacy_bundles.rb || echo "Privacy bundle fix script failed, continuing anyway..."
          
          cd ..
      
      - name: Fix privacy bundle build issues (Critical for Xcode 15+)
        script: |
          # CRITICAL FIX: Privacy bundle build failures
          # Affects: url_launcher_ios, sqflite_darwin, and other plugins with privacy manifests
          
          # Clean all corrupted build artifacts
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          
          # Force clean Flutter build cache
          flutter clean
          flutter pub get
          
          cd ..
          
      - name: Build iOS
        script: |
          # Use --release mode which has better plugin compatibility
          flutter build ipa --release \
            --export-options-plist /Users/builder/export_options.plist \
            --verbose