# Codemagic CI/CD Configuration for iOS Build - DEBUG MODE
workflows:
  default-workflow:
    name: iOS Build Debug
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.hggzk.app
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup code signing
        script: xcode-project use-profiles
          
      - name: Clean environment
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData ios/Pods ios/Podfile.lock
          echo "SWIFT_VERSION = 5.0" >> ios/Flutter/Generated.xcconfig
          
      - name: Install pods
        script: cd ios && pod install --repo-update && cd ..
      
      - name: Remove privacy bundles
        script: |
          cd ios
          ruby -e 'require "xcodeproj"; p=Xcodeproj::Project.open("Runner.xcodeproj"); p.targets.each{|t| next unless t.name=="Runner"; t.build_phases.each{|ph| ph.files.to_a.each{|f| ph.files.delete(f) if f.file_ref&&f.file_ref.path&&f.file_ref.path.include?("privacy.bundle")}}}; p.save' || true
          cd ..
          
      - name: Build iOS DEBUG
        script: flutter build ipa --debug --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ameenmamwn7@gmail.com
        notify:
          success: true
          failure: true
