# Codemagic CI/CD Configuration for iOS Build - DEBUG MODE
workflows:
  default-workflow:
    name: iOS Build Debug
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.hggzk.app
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup code signing
        script: xcode-project use-profiles
          
      - name: Clean environment
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData ios/Pods ios/Podfile.lock
          echo "SWIFT_VERSION = 5.0" >> ios/Flutter/Generated.xcconfig
          
      - name: Install pods
        script: cd ios && pod install --repo-update && cd ..
      
      - name: Fix privacy bundle issue (CRITICAL for Debug builds)
        script: |
          # ULTIMATE FIX: Directly edit the Xcode project file to remove privacy bundle references
          # This is the ONLY reliable way to fix this issue in Debug mode with Xcode 15+
          
          cd ios
          
          # Backup the original project file
          cp Runner.xcodeproj/project.pbxproj Runner.xcodeproj/project.pbxproj.backup
          
          # Remove ALL references to privacy bundles using perl
          # This removes the file references and build phase entries
          perl -i -pe 's/.*privacy\.bundle.*\n//g' Runner.xcodeproj/project.pbxproj
          
          echo "✅ Privacy bundle references removed from Xcode project"
          
          # Verify the changes
          if grep -q "privacy.bundle" Runner.xcodeproj/project.pbxproj; then
            echo "⚠️  Warning: Some privacy bundle references still exist"
          else
            echo "✅ All privacy bundle references successfully removed"
          fi
          
          cd ..
          
      - name: Build iOS DEBUG
        script: flutter build ipa --debug --export-options-plist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ameenmamwn7@gmail.com
        notify:
          success: true
          failure: true
