workflows:
  ios-workflow:
    scripts:
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
          
      - name: Fix Swift issues
        script: |
          # Clean build folder
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          
          # Set Swift version
          echo "SWIFT_VERSION = 5.0" >> ios/Flutter/Generated.xcconfig
          
      - name: Install pods
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate
          pod install --repo-update
          cd ..
          
      - name: Build iOS
        script: |
          flutter build ipa --debug --export-options-plist /Users/builder/export_options.plist